name: Push to AWS ECR

on:

  workflow_call:
    inputs:
      settings_xml:
        required: true
        type: string
      ecr_repo:
        required: true
        type: string  
      aws_region:
        required: true
        type: string              

jobs:
  PushToEcr:
    runs-on: ubuntu-latest
    env:
      SETTINGS_XML: ${{inputs.settings_xml}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
          cache: 'maven'
      # Install Maven
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          mvn -version

      # Prepare Integration Tests (H2 DB)
      - name: Create H2 database directory
        run: mkdir -p $HOME/h2

      - name: Set environment variable for H2 database path
        run: echo "H2_DATABASE=$HOME" >> $GITHUB_ENV

      # Run Maven build
      - name: Build with Maven
        env:
          H2_DATABASE: ${{ env.H2_DATABASE }}
        run: mvn clean install

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Add profile credentials to ~/.aws/credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_PEP }} --profile ${{ secrets.AWS_PROFILE }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_PEP }} --profile ${{ secrets.AWS_PROFILE }}

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        env:
          AWS_REGION: eu-west-2
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      

      - name: Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr_repo }}
          IMAGE_TAG: latest
        run: |
          mvn install -Pprod -Djib.httpTimeout=1800000 -Dcheckstyle.skip=true -DskipTests -Decr-service-repository=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
