name: Unit Tests

on:

  workflow_call:
    inputs:
      settings_xml:
        required: true
        type: string

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
          cache: 'maven'

      # Install Maven
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          mvn -version

      # Prepare Integration Tests (H2 DB)
      - name: Create H2 database directory
        run: mkdir -p $HOME/h2

      - name: Set environment variable for H2 database path
        run: echo "H2_DATABASE=$HOME" >> $GITHUB_ENV

      # Run Maven build
      - name: Build with Maven
        env:
          H2_DATABASE: ${{ env.H2_DATABASE }}
        run: mvn clean install

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests
        run: |
          mvn test
      # Upload Test Results as Artifacts
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: Maven-JUnit-test-results
          path: target/surefire-reports/*.xml

      - name: Archive Report
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: |
            target        
