name: Package

on:

  workflow_call:

jobs:
  Package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
          cache: maven

      # Install Maven
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          mvn -version

      # Prepare Integration Tests (H2 DB)
      - name: Create H2 database directory
        run: mkdir -p $HOME/h2

      - name: Set environment variable for H2 database path
        run: echo "H2_DATABASE=$HOME" >> $GITHUB_ENV

      # Run Maven build
      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-     

      - name: Download compiled classes
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target

      - name: Package
        env:
          H2_DATABASE: ${{ env.H2_DATABASE }}
        run: |
          mvn package -DskipTests

      - name: Archive packaged artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: |
            target/*.jar        
          
