name: Unit Tests

on:

  workflow_call:
    inputs:
      settings_xml:
        required: true
        type: string

jobs:
  Tests:
    runs-on: cawe-linux-x64-general-medium
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
          cache: 'maven'

      # Install Maven
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          mvn -version

      # Run Maven build
      - name: Build with Maven
        run: mvn clean install

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-     
      - name: Run tests
        run: |
          echo " $SETTINGS_XML " > settings.xml
          mvn --settings settings.xml test
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven JUnit test report
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
      - name: Archive Report
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: |
            target        
