name: Package

on:

  workflow_call:
    inputs:
      settings_xml:
        required: true
        type: string

jobs:
  Package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
          cache: maven

          # Install Maven
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          mvn -version

      # Run Maven build
      - name: Build with Maven
        run: mvn clean install

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-     

      - name: Download compiled classes
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target

      - name: Package
        env:
          SETTINGS_XML: ${{ inputs.SETTINGS_XML }}
        run: |
          echo " $SETTINGS_XML " > settings.xml
          mvn --settings settings.xml package -DskipTests

      - name: Archive packaged artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: |
            target/*.jar        
          
