name: Pre-Deploy Check

on:

  workflow_call:
    inputs:
      settings_xml:
        required: true
        type: string
   
jobs:   
  PreDeployCheck:
    runs-on: cawe-linux-x64-general-medium
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.6.0

      - name: Download compiled classes
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-          

      - name: Run release checks
        env:
          SETTINGS_XML: ${{ inputs.SETTINGS_XML }}
        run: |
          echo " $SETTINGS_XML " > settings.xml
          mvn --settings settings.xml -B -Drevision=1.0.0-SNAPSHOT -DdryRun=true -DskipTests release:prepare
          mvn --settings settings.xml release:clean
          
