name: Build

on:
  workflow_call:
    inputs:
      ecr_repo:
        required: true
        type: string
      to_promote:
        required: true
        type: boolean
    
jobs:
  Tests:
    name: Run unit tests
    uses: porqueeuprogramo/pep-workflows/.github/workflows/maven_test.yml@master
    secrets: inherit
    with:
      settings_xml: ${{inputs.settings_xml}}
    
  Package:
    name: Package JARs
    needs: Tests
    uses: porqueeuprogramo/pep-workflows/.github/workflows/maven_package.yml@master
    secrets: inherit
    with:
      settings_xml: ${{inputs.settings_xml}}

  PreDeployCheck:
    name: Pre-deploy check
    needs: [ Package ]
    uses: porqueeuprogramo/pep-workflows/.github/workflows/maven_pre_deploy_check.yml@master
    secrets: inherit
    with:
      settings_xml: ${{inputs.settings_xml}}

  PushToEcr:
    name: Push Image to ECR
    if: ${{ (inputs.to_promote) && (inputs.ecr_repo != '') }}
    needs: PreDeployCheck
    uses: porqueeuprogramo/pep-workflows/.github/workflows/aws_ecr_push.yml@master
    secrets: inherit
    with:
      settings_xml: ${{inputs.settings_xml}}
      aws_region: eu-west-2
      ecr_repo: ${{inputs.ecr_repo}}
